services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - "3306:3306"
    volumes:
      - mydb:/var/lib/mysql
    restart: always

  av:
    image: clamav/clamav:latest
    platform: linux/amd64
    ports:
      - "3310:3310"
    volumes:
      - /Users/username/repos/llm-image-blender/uploads:/app/uploads
    restart: always

volumes:
  mydb:
    name: "mysql-volume"
