services:
  app:
    build: .
    container_name: llm-image-blender
    platform: linux/amd64
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - av
    restart: always
  av:
    image: clamav/clamav:latest
    platform: linux/amd64
    ports:
      - "3310:3310"
    volumes:
      - ./uploads:/app/uploads
    restart: always

volumes:
  mydb:
    name: "mysql-volume"
